version: '3.4'

services:
  netframeworkdocker:
    ports:
      - "80"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  anothernetframeworkdocker:
    ports:
      - "80"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16


