version: '3.4'

services:
  anothernetframeworkdocker:
    image: anothernetframeworkdocker:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\roja_\source\repos\NetFrameworkDocker\AnotherNetFrameworkDocker:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800


  netframeworkdocker:
    image: netframeworkdocker:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\roja_\source\repos\NetFrameworkDocker\NetFrameworkDocker:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800


